version: '3'

services:
  main:
    image: nimmis/spigot
    volumes:
      - ./main:/minecraft
    ports:
      - '25565:25565'
    environment:
      - EULA=true
      - SPIGOT_VER=1.14.4
      - MC_MAXMEM=16g
    restart: always

