version: '3'

services:
  main:
    image: nimmis/spigot
    volumes:
      - ./main:/minecraft
    ports:
      - '25565:25565'
    environment:
      - EULA=true
      - SPIGOT_VER=1.14.4
      - MC_MAXMEM=16g
    restart: always

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: always

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/htpasswd:/etc/nginx/htpasswd
    ports:
      - 80:80

