version: '3'

services:
  main:
    image: nimmis/spigot
    volumes:
      - ./main:/minecraft
    ports:
      - '25565:25565'
    expose:
      - 8123
    environment:
      - EULA=true
      - SPIGOT_VER=1.14.4
      - MC_MAXMEM=3g
    restart: always

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/cadvisor.htpasswd:/etc/nginx/cadvisor.htpasswd
      - ./proxy/dynmap.htpasswd:/etc/nginx/dynmap.htpasswd
    ports:
      - '80:80'

